/** Strip markdown/LaTeX to readable plain text for PDF output. */
export function plain(md: string): string {
  return md
    .replace(/\$\$?([^$]+)\$\$?/g, (_, m: string) =>
      m
        .replace(/\\d?frac\{([^}]*)\}\{([^}]*)\}/g, "($1)/($2)")
        .replace(/\\tfrac\{([^}]*)\}\{([^}]*)\}/g, "$1/$2")
        .replace(/\\times/g, "x")
        .replace(/\\pi/g, "pi")
        .replace(/\\neq/g, "!=")
        .replace(/\\Rightarrow/g, "=>")
        .replace(/\\quad/g, " ")
        .replace(/\\text\{([^}]*)\}/g, "$1")
        .replace(/\\overline\{([^}]*)\}/g, "$1...")
        .replace(/\\mathbb\{Q\}/g, "Q")
        .replace(/\\pm/g, "+/-")
        .replace(/\\sqrt\{([^}]*)\}/g, "sqrt($1)")
        .replace(/\\[a-z]+/gi, "")
        .replace(/[{}]/g, "")
        .replace(/\^2/g, "²"),
    )
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/^>\s?/gm, "")
    .replace(/[✓]/g, "(ok)")
    .split("")
    .filter((character) => {
      const code = character.charCodeAt(0);
      return code <= 0xff || code === 0xb2;
    })
    .join("");
}

export async function downloadPdf(
  filename: string,
  title: string,
  sections: { heading?: string; body: string }[],
) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth(),
    H = doc.internal.pageSize.getHeight(),
    M = 50;
  let y = M;
  const line = (text: string, size: number, bold = false, gap = 6) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    for (const l of doc.splitTextToSize(text, W - M * 2) as string[]) {
      if (y > H - M) {
        doc.addPage();
        y = M;
      }
      doc.text(l, M, y);
      y += size + 4;
    }
    y += gap;
  };
  line(title, 18, true, 12);
  for (const s of sections) {
    if (s.heading) line(plain(s.heading), 13, true, 2);
    for (const para of plain(s.body)
      .split("\n")
      .filter((p) => p.trim())) {
      const h = /^#+\s/.test(para);
      line(para.replace(/^#+\s/, ""), h ? 12 : 10.5, h, 2);
    }
    y += 8;
  }
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by EduAI - always verify answers with your teacher.", M, H - 24);
  doc.save(filename);
}

export function downloadText(filename: string, text: string) {
  const url = URL.createObjectURL(new Blob([text], { type: "text/markdown" }));
  const a = Object.assign(document.createElement("a"), { href: url, download: filename });
  a.click();
  URL.revokeObjectURL(url);
}
