/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as DiagramsRouteImport } from './routes/diagrams'
import { Route as PptRouteImport } from './routes/ppt'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SolverRouteImport } from './routes/solver'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as VivaRouteImport } from './routes/viva'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeCheckRouteImport } from './routes/practice.check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramsRoute = DiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => rootRouteImport,
} as any)
const PptRoute = PptRouteImport.update({
  id: '/ppt',
  path: '/ppt',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SolverRoute = SolverRouteImport.update({
  id: '/solver',
  path: '/solver',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaRoute = VivaRouteImport.update({
  id: '/viva',
  path: '/viva',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookRoute,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeCheckRoute = PracticeCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => PracticeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/coding': typeof CodingRoute
  '/diagrams': typeof DiagramsRoute
  '/ppt': typeof PptRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/solver': typeof SolverRoute
  '/tutor': typeof TutorRoute
  '/viva': typeof VivaRoute
  '/book/$id': typeof BookIdRoute
  '/practice/check': typeof PracticeCheckRoute
  '/book/': typeof BookIndexRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coding': typeof CodingRoute
  '/diagrams': typeof DiagramsRoute
  '/ppt': typeof PptRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/solver': typeof SolverRoute
  '/tutor': typeof TutorRoute
  '/viva': typeof VivaRoute
  '/book/$id': typeof BookIdRoute
  '/practice/check': typeof PracticeCheckRoute
  '/book': typeof BookIndexRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/coding': typeof CodingRoute
  '/diagrams': typeof DiagramsRoute
  '/ppt': typeof PptRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/solver': typeof SolverRoute
  '/tutor': typeof TutorRoute
  '/viva': typeof VivaRoute
  '/book/$id': typeof BookIdRoute
  '/practice/check': typeof PracticeCheckRoute
  '/book/': typeof BookIndexRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/coding'
    | '/diagrams'
    | '/ppt'
    | '/practice'
    | '/progress'
    | '/settings'
    | '/solver'
    | '/tutor'
    | '/viva'
    | '/book/$id'
    | '/practice/check'
    | '/book/'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coding'
    | '/diagrams'
    | '/ppt'
    | '/progress'
    | '/settings'
    | '/solver'
    | '/tutor'
    | '/viva'
    | '/book/$id'
    | '/practice/check'
    | '/book'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/coding'
    | '/diagrams'
    | '/ppt'
    | '/practice'
    | '/progress'
    | '/settings'
    | '/solver'
    | '/tutor'
    | '/viva'
    | '/book/$id'
    | '/practice/check'
    | '/book/'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  CodingRoute: typeof CodingRoute
  DiagramsRoute: typeof DiagramsRoute
  PptRoute: typeof PptRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SolverRoute: typeof SolverRoute
  TutorRoute: typeof TutorRoute
  VivaRoute: typeof VivaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrams': {
      id: '/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof DiagramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppt': {
      id: '/ppt'
      path: '/ppt'
      fullPath: '/ppt'
      preLoaderRoute: typeof PptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solver': {
      id: '/solver'
      path: '/solver'
      fullPath: '/solver'
      preLoaderRoute: typeof SolverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viva': {
      id: '/viva'
      path: '/viva'
      fullPath: '/viva'
      preLoaderRoute: typeof VivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof BookRoute
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/check': {
      id: '/practice/check'
      path: '/check'
      fullPath: '/practice/check'
      preLoaderRoute: typeof PracticeCheckRouteImport
      parentRoute: typeof PracticeRoute
    }
  }
}

interface BookRouteChildren {
  BookIdRoute: typeof BookIdRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookIdRoute: BookIdRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface PracticeRouteChildren {
  PracticeCheckRoute: typeof PracticeCheckRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeCheckRoute: PracticeCheckRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  CodingRoute: CodingRoute,
  DiagramsRoute: DiagramsRoute,
  PptRoute: PptRoute,
  PracticeRoute: PracticeRouteWithChildren,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SolverRoute: SolverRoute,
  TutorRoute: TutorRoute,
  VivaRoute: VivaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
